# Generated by Django 3.0.5 on 2021-04-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='bio',
        ),
    ]
