# Generated by Django 3.0.5 on 2021-04-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20210424_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
