# Generated by Django 3.0.5 on 2021-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210426_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title_id',
        ),
    ]
