# Generated by Django 3.0.5 on 2021-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20210426_1012'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='author-title-constraint',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='author-title-constraint'),
        ),
    ]
